[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
mine_duel = "4b2q3K4cgr1P8FkjbcQ8nssDxLb9dhdVgVtrknvn5igJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./wallets/deployer.json"

[scripts]
test = "npm run ts-mocha -- --exit"
